-- 1. Create Participants Table
CREATE TABLE IF NOT EXISTS public.participants (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    nickname TEXT NOT NULL UNIQUE,
    email TEXT, -- Opcional
    phone TEXT,
    payment_status TEXT DEFAULT 'pending', -- 'pending', 'confirmed'
    payment_receipt_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Matches Table
CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jornada INTEGER NOT NULL,
    local_team TEXT NOT NULL,
    visitor_team TEXT NOT NULL,
    match_date TIMESTAMP WITH TIME ZONE NOT NULL,
    status TEXT DEFAULT 'pending', -- 'pending', 'finished'
    score_local INTEGER,
    score_visitor INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Quiniela Registrations Table
CREATE TABLE IF NOT EXISTS public.quiniela_registrations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    participant_id UUID NOT NULL REFERENCES public.participants(id) ON DELETE CASCADE,
    jornada INTEGER NOT NULL,
    payment_status TEXT DEFAULT 'confirmed', -- For Liga MX: defaults to 'confirmed' if participant is confirmed
    payment_receipt_url TEXT,
    points INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(participant_id, jornada)
);

-- 4. Create Forecasts Table (User Predictions)
CREATE TABLE IF NOT EXISTS public.forecasts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    registration_id UUID NOT NULL REFERENCES public.quiniela_registrations(id) ON DELETE CASCADE,
    match_id BIGINT NOT NULL REFERENCES public.matches(id) ON DELETE CASCADE,
    jornada INTEGER NOT NULL,
    prediction TEXT NOT NULL, -- 'L', 'E', 'V'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(registration_id, match_id)
);

-- 5. Create Settings Table
CREATE TABLE IF NOT EXISTS public.settings (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Insert Default Settings
INSERT INTO public.settings (key, value) VALUES
('prices', '{"tombola": 100, "quiniela": 100}'::jsonb),
('bank_details_quiniela', '{"banco": "Banco Ejemplo", "cuenta": "123456789", "clabe": "123456789012345678", "titular": "Organizador Quiniela", "zelle": "", "zelle_titular": "", "zelle_usd": 6}'::jsonb)
ON CONFLICT (key) DO NOTHING;

-- 7. Create Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_matches_jornada ON public.matches(jornada);
CREATE INDEX IF NOT EXISTS idx_registrations_participant_jornada ON public.quiniela_registrations(participant_id, jornada);
CREATE INDEX IF NOT EXISTS idx_forecasts_registration ON public.forecasts(registration_id);
CREATE INDEX IF NOT EXISTS idx_forecasts_match ON public.forecasts(match_id);
